[package]
name = "proto-json"
version = "0.1.0"
edition = "2021"


[lib]
proc-macro = true


[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.84"
quote = "1.0.36"
serde = { version = "1.0.196", features = ["derive"] }
syn = { version = "2.0.66", features = ["full"] }


